module.exports = {
  docsSidebar: [
    {
      type: 'category',
      label: 'In a hurry',
      items: [
        'in-a-hurry/introduction',
        'in-a-hurry/schema-evolution',
        'in-a-hurry/indexing-strategy',
      ],
    },
    {
      type: 'category',
      label: 'Path',
      items: ['path/learning-path', 'path/blogs-overview', 'path/schema-query-visuals', 'path/interactive-playground'],
    },
    {
      type: 'category',
      label: 'Case studies',
      items: [{type: 'autogenerated', dirName: 'case-studies'}],
    },
  ],
};
